server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  devtools:
    restart:
     exclude: "static/**,public/**"
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/db_centrohospitalar?useTimezone=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: root
    password: root

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000